services:
  medapp:
    build:
      context: ./medapp
      dockerfile: Dockerfile
    container_name: medfinder-app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mailpit
    restart: unless-stopped

  medapp-dev:
    build:
      context: ./medapp
      dockerfile: Dockerfile
      target: build
    container_name: medfinder-app-dev
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mailpit
    volumes:
      - gradle-cache:/root/.gradle
    working_dir: /app
    entrypoint: []
    command: ./gradlew bootRun --no-daemon
    develop:
      watch:
        - path: ./medapp/src/main/resources
          action: sync
          target: /app/src/main/resources
        - path: ./medapp/src/main/java
          action: rebuild

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # Mailpit Web UI
      - "1025:1025" # Mailpit SMTP Server

volumes:
  gradle-cache:
